# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-03 13:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('body', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('categorias', models.CharField(choices=[(b'0', b'Linux'), (b'1', b'dJango'), (b'2', b'Tutos')], default=b'0', max_length=6)),
            ],
        ),
    ]
